name: pytest-unit-tests

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  pytest:
    name: ${{ matrix.name }}
    runs-on: "${{ matrix.os }}"

    env:
      PYTHON_VERSION: "${{ matrix.python-version }}"
      TESTS: "tests/"

    strategy:
      # Prevent all build to stop if a single one fails
      fail-fast: false

      matrix:
        name: [
           python311-ubuntu2004,
           python312-ubuntu2204,
           python311-macOS
        ]
        include:
        - name: python311-ubuntu2004
          python-version: 3.11
          os: ubuntu-20.04

        - name: python312-ubuntu2204
          python-version: 3.12
          os: ubuntu-22.04

        - name: python311-macOS
          python-version: 3.11
          os: macos-latest

    steps:
    - name: Checkout simple_functions
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "${{ matrix.python-version }}"

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -e .
        pip install -r requirements.txt

    - name: Test with pytest
      run: |
        pytest tests/
